### ISSUE TITLE
Crashing on non-Linux machines

### ISSUE THREAD

**Issue by michakraus** [JuliaDiffEq/GeometricIntegratorsDiffEq.jl#2]
Hi Chris,

How did you find that GeometricIntegrators crashes on non-Linux machines? I am developing on macOS and never had such problems, it runs on Travis with both Linux and OSX, and one of my colleagues develops it on Windows. So if you have had any such issues it would be good to track it down and fix it.

Best,
Michael

**Comment by ChrisRackauckas** [comment]
That was when running it when that was written, which was some time last year. I see you updated so we'll get this updated.

**Comment by michakraus** [comment]
Ok, good. I also registered the package. Should become active within the next few days. Within the next week or two I can offer support for upgrades or so if needed. We can probably also add some more integrators that are available now to the interface. I will (try to) look into this next week.

**Comment by ChrisRackauckas** [comment]
Looks like that's all fixed up. Thanks.
