### ISSUE TITLE
Printing during simulations

### ISSUE THREAD

**Issue by ReneM92** [JuliaDiffEq/GeometricIntegratorsDiffEq.jl#9]
The following methods:

- GIImplicitEuler
- GIImplicitMidpoint
- GIRadIIA2
- GIRadIIA3
- GISRK3
- GIGLRK(s)

Print variables during simulation, for example: 
`i=0000043,    n=10000,   rₐ=1.18127730e-13,   rᵣ=7.38896254e-13,   rₛ=4.18842880e-15
  i=0000046,    n=10000,   rₐ=1.19015908e-13,   rᵣ=9.73603094e-13,   rₛ=2.94170772e-15
  i=0000051,    n=10000,   rₐ=1.75859327e-13,   rᵣ=1.65204179e-12,   rₛ=6.44117654e-15
  i=0000318,    n=10000,   rₐ=4.29517533e-15,   rᵣ=6.59407243e-12,   rₛ=1.30363626e-14
  i=0000321,    n=10000,   rₐ=3.83026943e-15,   rᵣ=7.69873466e-12,   rₛ=2.52486218e-14
  i=0000393,    n=10000,   rₐ=3.41393580e-15,   rᵣ=5.90737244e-11,   rₛ=1.38588572e-15
  i=0000454,    n=10000,   rₐ=1.55431223e-15,   rᵣ=3.18742176e-11,   rₛ=9.06174864e-16`

**Comment by ChrisRackauckas** [comment]
Seems like an upsteam issue?

**Comment by ChrisRackauckas** [comment]
This seems to be fixed.
